# This is a basic workflow to help you get started with Actions

name: actions
# 手动触发
on: workflow_dispatch
    
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Deno Run
        run: |
          git config --local user.email "${{secrets.EMAIL}}"
          git config --local user.name "Underglaze-Blue"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.ACCESS_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          deno run --unstable --allow-net --allow-read --allow-write index.ts
          git add .
          git commit -m "更新啦~"
          git push

